name: tap_google_analytics
version: "0.3.0"
require-dbt-version: [">=1.0.0", "<2.0.0"]

config-version: 2
vars:
  tap_google_analytics:
    schema: "{{ env_var('DBT_TARGET_SCHEMA') }}"

model-paths: ["models"]
analysis-paths: ["analysis"]
target-path: "target"
clean-targets: ["target"]
test-paths: ["test"]
seed-paths: ["data"]

models:
  tap_google_analytics:
    base:
      materialized: table
    transform:
      materialized: table
